[package]
name = "batch-converter"
version = "0.0.1"
authors = ["Alexander Chepurnov <inspired2@yandex.ru>"]

[lib]
name = "converter"
path = "src/lib.rs"

[[bin]]
name = "executable"
path = "src/bin.rs"

[dependencies]
image = "0.23.14"
rayon = "1.5.0"
[dev-dependencies]
cross = "0.2.1"
